"""CorpAction model — corporate action events affecting holdings.

Synced from Lixinger dividend endpoint (cash_dividend / stock_dividend /
capitalization) or detected heuristically (delist via company list diff).
Rights issues require manual entry (Lixinger has no reliable source).

Once processed_at is set, the corp_action has been applied to holdings
via a Trade(source='corp_action') linked through applied_trade_id.

Unique constraint on (stock_code, ex_date, action_type, source) prevents
duplicate sync.
"""
from datetime import date, datetime
from sqlalchemy import (
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import JSON

from app.db.base import Base
from app.core.datetime_utils import now


class CorpAction(Base):
    __tablename__ = "corp_actions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    stock_code: Mapped[str] = mapped_column(
        String, ForeignKey("stocks.code"), nullable=False, index=True
    )
    ex_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    """除权除息日 / 生效日."""

    action_type: Mapped[str] = mapped_column(String, nullable=False, index=True)
    """cash_dividend | stock_dividend | capitalization | rights_issue |
    delist | merger | code_change"""

    params_json: Mapped[dict] = mapped_column(JSON, nullable=False)
    """Type-specific params. Examples:
    - cash_dividend: {"per_share": 0.5, "record_date": "2026-06-15"}
    - stock_dividend: {"per_10_shares": 5}
    - capitalization: {"per_10_shares": 10}
    - rights_issue: {"per_10_shares": 3, "subscription_price": 8.0,
                     "subscription_end": "2026-07-01"}
    - delist: {"reason": "...", "last_trade_date": "..."}
    - merger: {"new_code": "...", "ratio": 0.8}
    - code_change: {"new_code": "..."}
    """

    source: Mapped[str] = mapped_column(
        String, nullable=False, default="lixinger", server_default="lixinger"
    )
    """lixinger | manual | heuristic (company list diff)"""

    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=now(), nullable=False
    )
    processed_at: Mapped[datetime | None] = mapped_column(
        DateTime, nullable=True, index=True
    )
    """Null = pending; non-null = applied."""

    applied_trade_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("trades.id"), nullable=True
    )
    """The Trade generated by applying this CorpAction. None if not yet
    applied or if no trade was needed (e.g. delist marks holding only)."""

    note: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        UniqueConstraint(
            "stock_code",
            "ex_date",
            "action_type",
            "source",
            name="uq_corp_actions_natural_key",
        ),
        Index("ix_corp_actions_pending", "ex_date", "processed_at"),
    )
