"""Draft model — actionable buy/sell suggestion.

A Draft is generated by plan_runner when trading rules fire for a candidate
stock that is in the watchlist. The user reads it, places the order with their
broker, then marks it executed.
"""

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.core.datetime_utils import now

if TYPE_CHECKING:
    from app.models.plan import Plan


class Draft(Base):
    __tablename__ = "drafts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    plan_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("plans.id"), nullable=True, index=True
    )
    """NULL for system-generated drafts (M4 thesis_breach sells); otherwise FK to plans.id."""
    code: Mapped[str] = mapped_column(
        String, ForeignKey("stocks.code"), nullable=False, index=True
    )

    side: Mapped[str] = mapped_column(String, nullable=False)  # BUY | SELL
    status: Mapped[str] = mapped_column(
        String, nullable=False, default="pending", index=True
    )  # pending | executed | cancelled | superseded

    step_kind: Mapped[str] = mapped_column(String, nullable=False)  # buy_ladder | sell_ladder
    step_index: Mapped[int] = mapped_column(Integer, nullable=False)

    add_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    reduce_pct_of_position: Mapped[float | None] = mapped_column(Float, nullable=True)

    suggested_quantity: Mapped[int | None] = mapped_column(Integer, nullable=True)
    """Auto-computed suggested buy quantity (multiple of 100). Filled by
    plan_runner using position_sizing_service. None for SELL or when sizing fails."""

    reason: Mapped[str] = mapped_column(Text, nullable=False)
    """Human-readable explanation: which trigger fired, observed vs threshold."""

    source: Mapped[str] = mapped_column(String, nullable=False, default="evaluator")
    """Origin: 'evaluator' | 'rebalance' | 'manual'"""

    triggered_at: Mapped[datetime] = mapped_column(
        DateTime, default=now(), index=True
    )
    executed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    __table_args__ = (
        Index("ix_drafts_idempotent", "plan_id", "code", "step_kind", "step_index", "status"),
    )

    plan: Mapped["Plan"] = relationship(back_populates="drafts")
